# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
  - id: flake8
    name: flake8
    entry: flake8
    language: python
    types: [python]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: detect-private-key
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/python-poetry/poetry
  rev: 1.8.3
  hooks:
  - id: poetry-lock
  - id: poetry-export
    args: ["-f", "requirements.txt"]
  - id: poetry-export
    args: ["--dev", "-f", "requirements.txt", "-o", "requirements-dev.txt"]
files: (fds/|tests/|poetry.lock)
