name: Check licenses

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-licenses:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dagshub/python-license-checker-action@v1
